- README.md
Rekhchand Sahu
https://rekhchandsahu.com/
NaN
- React
- Preact
- GSAP
- Gatsby
> 🔥Add Rekhchand's portfolio

- README.md
Thang Huu Vu
https://www.thvu.dev
https://github.com/ThangHuuVu/thvu-blog
- React
- NextJS
- TypeScript
- NodeJS
- Tailwindcss
- GraphQL
> :fire: Add Thang's portfolio

- README.md
Aditya Vikram
https://people.umass.edu/avsingh/
https://github.com/AVS1508/My-Alternate-Portfolio-Website
- HTML
- CSS
- JavaScript
> :fire: Add Aditya's portfolio

- README.md
Dejan Markovic
https://www.dejan.works
None
- HTML
- CSS
- JavaScript
- jQuery
> :fire: Add Dejan's portfolio

- README.md
Max Böck
https://mxb.dev
https://github.com/maxboeck/mxb
- Eleventy
- Nunjucks
- SCSS
> :fire: Add max's profile

- README.md
Rafael Conde
https://rafa.design/
None
- HTML
- CSS
- JavaScript
- Netlify
> 🔥 Add Rafael's portfolio

- README.md
Bruno Simon
https://bruno-simon.com/
Not available
- GSAP
- ThreeJS
- JavaScript
> :fire: Add Bruno's portfilio

- README.md
Oluwadare Oluwaseyi
https://www.seyi.dev/
https://github.com/oluwadareseyi/folio-v2
- HTML
- SCSS
- JavaScript
- GSAP
> :fire: Add Seyi's portfolio

- README.md
Jason Lengstorf
https://www.jason.af/
https://github.com/jlengstorf/jason.af
- JavaScript
- TypeScript
- NunJucks
- CSS
> :fire: Add Jason's portfolio

- README.md
Chris Potter
https://madebyporter.com/
https://github.com/madebyporter/madebyporter
- HTML
- Ruby
- JavaScript
- SCSS
- CSS
- Jquery
- Slim
> :fire: Add Chris's portfolio

- README.md
Louis Hoebregts
https://www.mamboleoo.be
None
- PHP
- Parcel
> :fire: Add Louis portfolio

- README.md
> :fire: Add Adrien's portfolio

- README.md
Aaron Shapiro
https://www.aaron.mn/
https://github.com/aarshap/aaron.mn
- React
- Gatsby
- Styled Components
- Netlify
> :fire: Add Aaron's portfolio

- README.md
Peter Tait
https://petertait.com/
https://github.com/petertait/petertait.com
- React 
- Netlify
- Radium
- Webpack
> :fire: Add Peter's portfolio

- README.md
Rick Waalders
https://www.rickwaalders.com/
None
- React
- NextJS
- Webpack
- NodeJS
- Netlify
> :fire: Add Rick's portfolio

- README.md
Ahmed Zougari
[ahmedzougari.netlify.app](https://ahmedzougari.netlify.app/)
[Github](https://github.com/zougari47/portfolio-template)
HTML, SASS, Bootstarp, JavaScript
> add Ahmed Zougari portfolio

- README.md
Raj Savaliya
https://www.rajsavaliya.com/
https://github.com/SRX9/portfoliosrx9
NextJS, React, TypeScript, Tailwind CSS
> Added a Visual Studio Code Theme Dev Portfolio

- README.md
Nirban Chakraborty
[Portfolio Link](https://nirban-chakraborty.netlify.app/)
[Github](https://github.com/nirban256/personal_website)
ReactJs, JavaScript, SASS, HTML
> Added my portfolio details

- README.md
Md Nayeem Hossain
https://nayeemdev.github.io/
https://github.com/nayeemdev/nayeemdev.github.io
HTML, CSS, Bootstrap, Javascript, jQuery
> Added Md Nayeem's Portfolio

- README.md
Jeferson S. Brito
https://www.jefersonsilva.me/
https://github.com/jeferson-sb/portfolio
Vue + Vite = ❤
> Add Jeferson's Portfolio

- README.md
Dale Larroder
[dalelarroder.com](https://www.dalelarroder.com/)
N/A
NextJS, Preact, TypeScript, Tailwind, MDX
> add dalelarroder.com

- README.md
> added new portfolio 'williamssam'

- README.md
Leonel Ngoya
https://lndev.me
https://github.com/ln-dev7 
HTML CSS JS
> add ln-dev portfolio

- .github/ISSUE_TEMPLATE/feature.md
> 🎯 Add feature template

- README.md
Number 84
Segun Ajibola
www.segunajibola.com
https://github.com/segunajibola/portfolio
HTML, CSS, TailwindCSS, React, SwiperJS
> Add portfolio

- README.md
Dennis Snellenberg
https://dennissnellenberg.com/
None
GSAP, Vue, PHP
> 🔥 Add Dennis portfolio

- README.md
Isaac Fayemi
https://www.fayemi.design/
None
Vanilla JS, pug, Prismic CMS, SCSS, threejs, GSAP.
> Add Isaac Fayemi's portfolio

- README.md
Lazar Nikolov
[nikolovlazar.com](https://nikolovlazar.com)
[nikolovlazar/nikolovlazar.com](https://github.com/nikolovlazar/nikolovlazar.com)
- Next.js
- Chakra UI
- MDX
- Prisma
- PlanetScale
> Adding nikolovlazar.com

- README.md
Patrick Scott
https://pscott.io
None
React.js, Heroku and Github Pages
> Adding pscott.io

- README.md
Lee Robinson
https://leerob.io/
https://github.com/leerob/leerob.io
Next.js, PlanetScale, Prisma, Vercel, Sanity, Tailwind CSS
> 🔥 Add Lee's portfolio

- README.md
Parth Desai
https://musing.vercel.app/
https://github.com/pycoder2000/blog
TailwindCSS, React, Javascript, Next.JS, MDX, Mailchimp Newsletter, Gisqus Comments
> Added parth desai's site

- README.md
Payton Pierce
https://paytonpierce.dev
https://github.com/paytonjewell/paytonpierce.dev
React, Material UI
> added my portfolio to the list

- README.md
@JacobFV, @alshedivat
https://jacobfv.github.io
https://github.com/JacobFV/jacobfv.github.io
HTML, Jekyll
> Added jacobfv.github.io portfolio

- README.md
Phillip Cabrera
https://pcabreram-portfolio.netlify.app/
https://github.com/pcabreram1234/portfolio
HTML, CSS, JavaScript, Webpack, ReactJs
> My Portfolio added.

- README.md
Nahuel Carrizo
https://nahuel61920.github.io/portafolio-Nahuel/
https://github.com/Nahuel61920/portafolio-Nahuel
HTML, CSS, JavaScript, React, Webpack, Github Pages
> Adding portfolio nahuel61920

- README.md
Alfaizkhan Pathan
alfaizkhan.github.io
https://github.com/Alfaizkhan/Alfaizkhan.github.io
Flutter, Dart, JavaScript, Github Pages
> Added my portfolio-page => alfaizkhan.github.io

- README.md
> Added jatinkamboj.me

- CONTRIBUTING.md
Linked code_of_conduct.md to contributing.md
> Linked code_of_conduct

- README.md
Ara Oladipo
https://araoladipo.tech/
https://github.com/Ara-O/Portfolio-Website
HTML, CSS, Javascript, Vue.js, Spline3D
> Adding my portfolio

- README.md
Add [@all-contributors](https://allcontributors.org/docs/en) bot for recognizing contributors to the project.
> feat: :robot: add contributors bot to recognize contributors

- README.md
@all-contributors please add @Evavic44 for maintenance, code, review, bugs
> fix: add defualt all-contributors badge

- README.md
Seems all-contributors follows a strict no-indent rule. So I removed every indent made by prettier.
> **Hopefully, this works.**
> fix: remove prettier indent from all-contributors file

- README.md
Anthony Fu
https://antfu.me/
https://github.com/antfu/antfu.me
- VueJS
- Markdown
- TypeScript 
- CSS
- HTML
#104
> feat: add anthony portfolio

- README.md
Mike Bifulco
https://mikebifulco.com/
https://github.com/mbifulco/blog
- NextJS
- React
- SCSS
- MDX
> feat: add mike bifulco's portfolio

- README.md
> add abhishekjha

- README.md
Wallace Nascimento
[Link](https://portfolio-srnascimento40.vercel.app)
[Portfolio](https://github.com/SrNascimento40/portfolio)
NextJS, ReactJS, Typescript and Styled-components.
> feat: Add Nascimento's portfolio

- CONTRIBUTING.md
> Issue #169 resolved

- README.md
Khaled Mohamed
https://portfolio-john2.netlify.app/
None
HTML5, SCSS, Bootstrap5, JavaScript, SwipperJS, Netlify
> Add John Doe portfolio

- README.md
- Piyush Goyani
- https://piyushgoyani.thesourcepedia.org
- None
- VueJS, Gridsome, TailwindCSS, Firebase
> Add Piyush Goyani's Portfolio

- README.md
Vanessa Toledo Santana
https://www.nessajs.com.br/
https://github.com/vanessa-dev/nessa.js
HTML, CSS, JavaScript and PHP
> feat: Add  Vanessa's Portfolio

- README.md
Ajo Alex
[Live Url](https://devpenzil.dev/)
[Github](https://github.com/devpenzil/devpenzil.dev)
NextJs, Tailwind, GraphCMS
> added devpenzil portfolio

- .github/Pull_request_template.md
> feat: update portfolio author details

- .github/workflows/autodeploy.yml
- README.md
- docs/portfolio.md
Testing auto deploy on a fake branch
#222
> testing github action auto deploy

- .github/workflows/autodeploy.yml
- README.md
Hey,
As per our discussion in #220 I have setup the workflow, tested it and it works. 🎉
You can check the successful [action run log here](https://github.com/vimode/portfolio-ideas/actions/runs/3995636766/jobs/6854738185) 🔍
And the updated [`portfolio.md` from the successful](https://github.com/vimode/portfolio-ideas/blob/workflow/autodeploy/docs/portfolio.md) action run. 
As of now for the test, its limited to pushes to this branch.
But what do you think will be better? Run the action to pushes only to `main` branch so only when you merge it to `main` or make it so that for all the pushes? 
The second option has the advantage for the contributor to see the preview build too!
Let me know if the workflow looks good; the name of the workflow, the commit message and all the steps.
I will …
> feat: autodeploy workflow added

- CONTRIBUTING.md
> docs: clarify contributing steps

- docs/contributors.md
- docs/guide.md
Fixes Evavic44/portfolio-ideas#273
> docs: add Contributors and Guide pages to Doc site

- README.md
This PR updates the shields.io link. 
The purpose of this update is to avoid the need for manual number updates.
https://github.com/Evavic44/portfolio-ideas/blob/af38acdb1a701f243fd645b55c0f764e952c8b4d/README.md?plain=1#L15
- [GitHub contributors (via allcontributors.org) | Shields.io](https://shields.io/badges/git-hub-contributors-via-allcontributors-org-1)
> chore: update shields.io link

- README.md
> Added my portfolio

- README.md
@LNLenost
https://lnlenost.netlify.app/
https://github.com/LNLenost/lnlenost.github.io
HTML, SASS, JavaScript
> Add LNLenost

- README.md
@tsolutionsx 
https://techsolutionsx.vercel.app/
None
NextJS, TailwindCSS
> Add TSolutions portfolio

- README.md
@priyanshtiwari001
https://priyanshu-tiwari.vercel.app/
https://github.com/priyanshtiwari001/portfolio
NextJS, TailwindCSS, TypeScript, ThreeJS
> Add Priyanshu portfolio

- README.md
@yodkwtf
https://yodkwtf.com/
https://github.com/yodkwtf/yodkwtf.com
ReactJS, CSS, Airtable CMS, Context API
> Add Durgesh's portfolio
